### PR TITLE
65 reorder and add hyperlinks to supporter logos

### PR DESCRIPTION
**Pull request by a-wong-8**

### CODE REVIEW

**Comment by a-wong-8** [comment]
Screenshot 2024-09-26 at 12 03 03 PM
Screenshot 2024-09-26 at 12 02 39 PM

**Comment by gevuong** [comment]
I added padding because the logos were extremely close to each other.

Also, I tried clicking outside of footer modal (below modal) but it doesn't seem to work.
If it's not a quick fix, I suggest creating a separate ticket and PR to add that enhancement instead of lumping it in this supporter logo PR.

**Comment by a-wong-8** [comment]
> I added padding because the logos were extremely close to each other.
> 
> Also, I tried clicking outside of footer modal (below modal) but it doesn't seem to work. If it's not a quick fix, I suggest creating a separate ticket and PR to add that enhancement instead of lumping it in this supporter logo PR.

I can fix, no problemo

**Comment by gevuong** [comment]
It still doesn't work when you click underneath modal for mobile views

https://github.com/user-attachments/assets/dfc62a1e-f90f-42eb-a6d1-ef53a189669a

**Comment by gevuong** [comment]
> > I added padding because the logos were extremely close to each other.
> > Also, I tried clicking outside of footer modal (below modal) but it doesn't seem to work. If it's not a quick fix, I suggest creating a separate ticket and PR to add that enhancement instead of lumping it in this supporter logo PR.
> 
> I can fix, no problemo ... es simple fix

It still doesn't work when you click underneath modal for mobile views..

https://github.com/user-attachments/assets/dfc62a1e-f90f-42eb-a6d1-ef53a189669a

**Comment by a-wong-8** [comment]
nobody has a phone that long ... -_-

**Comment by gevuong** [comment]
Regardless of how long the screen is, the modal does not close using mobile phone dimensions..

If you're not sure how to fix it, I would revert to my original suggestion and remove the feature so we can move forward and merge and the support logo updates.

**Comment by a-wong-8** [comment]
ok it's removed

**Review by gevuong — APPROVED** [review]

**Comment by a-wong-8** [comment]
@gevuong thanks for the fixes

**Pull request merged**
