### PR TITLE
removed footer nav links and all associated components

### PR DESCRIPTION
**Pull request by a-wong-8**
Screenshot 2024-11-24 at 9 46 01 AM

### CODE REVIEW

**Comment by gevuong** [comment]
@a-wong-8 I'm wondering if the Virufy logo on the left should be removed, as I think it's part of the footer navbar

**Comment by a-wong-8** [comment]
Maybe we should ask ui team?

**Comment by gevuong** [comment]
@a-wong-8 Lets remove the logo as it does "navigate" to the home page and duplicates functionality in the header navbar.

**Comment by a-wong-8** [comment]
Screenshot 2024-11-25 at 2 29 58 PM

**Review by gevuong — APPROVED** [review]
I pushed minor styling changes. Take a look and if you think it's ready, go ahead and merge it.

**Pull request merged**
