### PR TITLE
41 refactor home page multi language support

### PR DESCRIPTION
**Pull request by a-wong-8**
- added multi language support for home page 
- moved all code from section2 and section3 into home page
- refactored code and removed [ ] from tailwind and replaced w correct tailwind syntax
- deleted section2 and section3 components

### CODE REVIEW

**Comment by gevuong** [comment]
Thanks for refactoring! Are you able to change the "Virufy" text to green in subText and subText2? If you're wondering how it can be done, the `/ai` and `/faq` page has something similar implemented.

**Comment by a-wong-8** [comment]
> Thanks for refactoring! Are you able to change the "Virufy" text to green in subText and subText2? If you're wondering how it can be done, the `/ai` and `/faq` page has something similar implemented.

Yup, done! @gevuong

**Comment by gevuong** [comment]
Can you use the existing TypeText interface instead of creating new ones?
The less code duplication the better.

**Comment by gevuong** [comment]
> > Thanks for refactoring! Are you able to change the "Virufy" text to green in subText and subText2? If you're wondering how it can be done, the `/ai` and `/faq` page has something similar implemented.
> 
> 
> 
> Yup, done! @gevuong 

Cool! Can you use the existing TypeText interface instead of creating new ones to reduce code duplication?

**Comment by a-wong-8** [comment]
@gevuong yeah. did some refactoring too

**Comment by a-wong-8** [comment]
@gevuong ai ts should use TypeText as well lol

**Review by gevuong — APPROVED** [review]

**Comment by gevuong** [comment]
I made minor changes to address `Warning: Each child in a list should have a unique "key" prop.`, and README.

**Pull request merged**
