### PR TITLE
55 style 3 footer modals to match design system

### PR DESCRIPTION
**Pull request by a-wong-8**
1. styled footer modals to match figma
2. reused AccordianItem component from FAQ for footer modals

### CODE REVIEW

**Review by gevuong — COMMENTED** [review]
Due to limited time, I'm not able to review the entire PR but this is what I gathered:

1. I don't recommend adding HTML w/ Tailwind in metadata because we want separation of concern between metadata, HTML w/ Tailwind. If someone needed to update the styling, HTML, or debug, we want them to view and edit the React component, not the metadata. If there isn't a better solution, I would revert it to what it was before.
2. Are there alternatives to using `dangerouslySetInnerHTML`? Based on research, it's typically avoided unless it's necessary. In the case of simply rendering static content in a modal, I would prefer using an alternative method of rendering content.
3. Accordion is misspelled.

**Comment by a-wong-8** [comment]
> Due to limited time, I'm not able to review the entire PR but this is what I gathered:
> 
> 1. I don't recommend adding HTML w/ Tailwind in metadata because we want separation of concern between metadata, HTML w/ Tailwind. If someone needed to update the styling, HTML, or debug, we want them to view and edit the React component, not the metadata. If there isn't a better solution, I would revert it to what it was before.
> 2. Are there alternatives to using `dangerouslySetInnerHTML`? Based on research, it's typically avoided unless it's necessary. In the case of simply rendering static content in a modal, I would prefer using an alternative method of rendering content.
> 3. Accordion is misspelled.

@gevuong ok items corrected

**Review by gevuong — COMMENTED** [review]
Thanks for updating.

A few things I noticed:

1. When screen width shrinks, the content appears to get cut off.

Screenshot 2024-09-02 at 8 38 37 PM

2. Can you add some left padding to the bullet point content?
Screenshot 2024-09-02 at 8 46 59 PM

3. I cannot see the remaining content in the 6th question of Cookie Policy.
Screenshot 2024-09-02 at 8 48 06 PM

4. In Cookie Policy, the transition when opening and closing the accordion doesn't seem to work consistently compared to the accordions in "Privacy Policy" and "Do Not Sell My Personal Info". Also, the up/down arrows appear squished. Is that expected behavior?

5. Bonus: If you have time, adding the ability to close modal by clicking outside of it would be great. I think giving users the flexibility to close modal with mouse click can improve user experience since only static content is displayed. If it was a login or form modal, I would probably not suggest this.

**Comment by a-wong-8** [comment]
1. I changed the max-h- to max-h-full
2. added left padding
3. fixed max-h for 6th question 
4. i'm not sure why the transition does not work most of the time - I think it has to do with the max-h. the arrow looks ok on my end (chrome). any suggestions for the transition?
5. this might take too much time

**Review by gevuong — APPROVED** [review]

**Pull request merged**
