### PR TITLE
101 update style to match figma

### PR DESCRIPTION
**Pull request by a-wong-8**

### CODE REVIEW

**Comment by gevuong** [comment]
@a-wong-8 
There's a visible line underneath the navbar. I think removing `shadow` in the `nav` element will fix this.

Screenshot 2024-11-23 at 2 13 17 PM


Also, why did you decide to remove the arrow icon in the locale selector?

**Comment by a-wong-8** [comment]
That line has always been there lol. I added the arrow but I was having issues making it not show up w the mobile view so I removed it. Was going to work on it later as it was getting late.

**Comment by gevuong** [comment]
According to Figma, mobile view should have an arrow as well

**Comment by a-wong-8** [comment]
originally there was no arrow in desktop view... somebody added it

**Comment by gevuong** [comment]
I added the arrow icon in mobile and desktop view. I'm going to approve MR, but please review my changes. If it looks good, merge it.

**Review by gevuong — APPROVED** [review]

**Pull request merged**
