### PR TITLE
added shirin to advisors

### PR DESCRIPTION
**Pull request by a-wong-8**
Screenshot 2024-11-29 at 10 09 43 AM

### CODE REVIEW

**Comment by a-wong-8** [comment]
chore: add hyperlink to shirin once pr for hyperlinks is approved

**Comment by gevuong** [comment]
@a-wong-8 I'll review once other PRs are merged and this branch is up-to-date, and a hyperlink is added to Shirin.

**Comment by a-wong-8** [comment]
ok ready for review

**Review by gevuong — APPROVED** [review]
Pushed minor changes. Take a look and merge if it looks good

**Pull request merged**
