### PR TITLE
88 update all advisor and team lead images

### PR DESCRIPTION
**Pull request by a-wong-8**
changed style for advisors and oyw team lead imgs as per figma.

### CODE REVIEW

**Review by gevuong — COMMENTED** [review]
The images appear thin
Screenshot 2024-11-06 at 10 54 03 AM

**Comment by a-wong-8** [comment]
can you inlcude the screen size px

**Comment by gevuong** [comment]
Nvm, I rebuilt and refreshed and it looks good. Based on Figma, the font size of the title should be smaller than the name, and be about the same as the description.

**Comment by a-wong-8** [comment]
ok corrected 
Screenshot 2024-11-06 at 2 27 29 PM

**Comment by gevuong** [comment]
It looks like the images overlap at 320px, and at 375px, the images could use a little more spacing between each other, similar to what's currently in production.

I think it would be ideal if the spacing looked similar to the mobile view currently in production.

**Comment by a-wong-8** [comment]
sorry i forgot to check small mobile view ha

**Comment by gevuong** [comment]
At 767px and below, the images appear too short and one of the images is no longer as wide.
I would either switch to mobile view image sizes, similar to what's currently in production, or figure out how to retain the original desktop image sizes at 767px and below then switch to mobile image size when screen width gets too small.

Screenshot 2024-11-06 at 6 35 31 PM

**Comment by a-wong-8** [comment]
ok I think I got it 😮‍💨

**Review by gevuong — APPROVED** [review]
I'm going to approve it, but I would suggest you review my changes before merging.

I addressed the following: 
- closes #96 
- Reduced vertical padding of banner underneath advisors and team leads because it more closely aligns with Figma design.

**Pull request merged**
