### PR TITLE
Fix#76

### PR DESCRIPTION
**Pull request by devfercastro**
- [x]  1.  Can't read "Your Digital Health Companion" on home page as the font is the same color as the waveform.
- [ ]  2. Text is not centered on home page: "Introducing Virufy, the cutting-edge app that ..." Some weird line breaks happeneing
- [x]  3. Remove "Empower yourself with the latest in health technology." on home page, not adding value
- [x]  4. "*The app is still under development, support us by contributing your data into our data collection app." => "*The app is still under development, support us by contributing your cough sounds into our data collection app."
- [x]  5. "Receive immediate prompt feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough*" =>"Rapid feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough"
- [x]  6. Increase font size of "*The results of the analysis done by the system will not replace the diagnosis by a specialized doctor." and replace to say "Virufy will not take place of a doctor and would like to remind you it is your responsibility to seek medical advice from your doctor."
- [x]  7. Replace "Artificial Intelligence (AI) is capable of detecting tiny differences in vocal patterns to detect disease presence." = > "Artificial Intelligence (AI) is capable of detecting minute differences in vocal patterns to detect disease presence."
- [x]  8. Increase font size "Our groundbreaking app employs cutting-edge AI technology to analyze your breathing patterns  using deep learning algorithms and audio signal processing techniques."

### CODE REVIEW

**Comment by devfercastro** [comment]
@gevuong would you mind?

**Comment by devfercastro** [comment]
I tried the second task, but the changes led to other changes, which led to more changes, and so on. So I decided to pass.

**Comment by gevuong** [comment]
Ic ok, no worries. @a-wong-8 is currently refactoring the home page for Issue #41. He and I can take a look at Task 2 afterwards. I appreciate you trying tho!

Quick update regarding Tasks 1 and 8 after discussing with design team:

**Task 1**: The text should be either above or below the soundwave, is it possible to do this on all devices? If not we can either 1) Change the font to white as well, or 2) Remove the soundwave/make it darker.

**Task 8**: 
- [ ] For both paragraphs under `How does AI Work?` in `/ai` page, the paragraph texts can be set to `text-base md:text-xl`. 
- [ ] I just noticed this: the first letter in `Work` in `How does AI Work?` should be lowercased.

If you don't have time or want to continue working on it, just lmk and I'll review what your have so far. Thank you!

**Comment by devfercastro** [comment]
- [x]  1.  Can't read "Your Digital Health Companion" on home page as the font is the same color as the waveform. (Needs review)
   - add @media for 950px displays, that applies a mt of 8rem to .custom-top-margin
   - change the margin top in @media of 1200px from 15rem to 13rem
   - set image opacity to 0.65 ("subText" it's over soundwave on different displays)
- [ ]  2. Text is not centered on home page: "Introducing Virufy, the cutting-edge app that ..." Some weird line breaks happeneing
- [x]  3. Remove "Empower yourself with the latest in health technology." on home page, not adding value
- [x]  4. "*The app is still under development, support us by contributing your data into our data collection app." => "*The app is still under development, support us by contributing your cough sounds into our data collection app."
- [x]  5. "Receive immediate prompt feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough*" =>"Rapid feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough"
- [ ]  6. Increase font size of "*The results of the analysis done by the system will not replace the diagnosis by a specialized doctor." and replace to say "Virufy will not take place of a doctor and would like to remind you it is your responsibility to seek medical advice from your doctor."
- [x]  7. Replace "Artificial Intelligence (AI) is capable of detecting tiny differences in vocal patterns to detect disease presence." = > "Artificial Intelligence (AI) is capable of detecting minute differences in vocal patterns to detect disease presence."
- [x]  8. Increase font size "Our groundbreaking app employs cutting-edge AI technology to analyze your breathing patterns  using deep learning algorithms and audio signal processing techniques."

**Comment by gevuong** [comment]
@a-wong-8 do you mind reviewing all the changes we made?

- [ ] 6. Increase font size of "*The results of the analysis done by the system will not replace the diagnosis by a specialized doctor." and replace to say "Virufy will not take place of a doctor and would like to remind you it is your responsibility to seek medical advice from your doctor."

I'm thinking we can create a separate ticket for this (or include it to #41 - home page refactor) so we can close this PR.
- [ ] 2. Text is not centered on home page: "Introducing Virufy, the cutting-edge app that ..." Some weird line breaks happeneing

**Comment by devfercastro** [comment]
I'll try that one again, if it's not ready by tomorrow feel free to close the PR.

**Review by a-wong-8 — COMMENTED** [review]
excellent work @devfercastro 
I think it would look better if we moved the 'Welcome to Virufy' and 'Your Digitial...' above the waveform, that way we can remove the opacity which is making the bg img too dark.

**Comment by devfercastro** [comment]
Sure, no problem.

**Comment by devfercastro** [comment]
You mean living it like this but for all display sizes?

**Comment by devfercastro** [comment]
Sure and thanks that helps a lot.

**Review by a-wong-8 — DISMISSED** [review]
excellent work @devfercastro and @gevuong

**Comment by devfercastro** [comment]
Jajaja me caí a pedazos. But I finally got my first open source contribution.

**Comment by gevuong** [comment]
@devfercastro thanks for making the changes to show text beneath hand. However, it now looks like the changes are overlapping with the text beneath it, starting at `976px`.

Would any of you be able to fix this? If not, I may move it to a new issue. Or include it to https://github.com/gevuong/minimal-i18n-with-app-router/issues/41 - home page refactor). Lmk.

Screenshot 2024-10-09 at 12 47 07 PM

**Comment by devfercastro** [comment]
@gevuong Sure not problem

**Comment by gevuong** [comment]
I think it looks good. @a-wong-8 do you mind reviewing it once more?

**Review by a-wong-8 — APPROVED** [review]
good job @devfercastro & @gevuong

**Comment by gevuong** [comment]
@devfercastro thank you for contributing!

**Comment by devfercastro** [comment]
@gevuong thanks to you guys for being so patient.

**Pull request merged**
