### PR TITLE
News page 

### PR DESCRIPTION
**Pull request by a-wong-8**
1.  renamed press release page to News
2.  added 11 news articles from https://virufy.org/news to News page
3.  created redirect to news page from https://virufy.org/press

### CODE REVIEW

**Review by gevuong — APPROVED** [review]

**Comment by gevuong** [comment]
@a-wong-8 Oh just read Slack msgs, sounds like they want 2 columns instead of one? I wonder what they prefer for mobile view.

**Comment by a-wong-8** [comment]
localhost_3000_en_news (1)
localhost_3000_en_news (2)

**Comment by gevuong** [comment]
Can you have "Read More" be in a single line, and have the text in each card align horizontally with the text in its neighboring card? Content in some of the cards appear higher than the content in other cards.

Screenshot 2024-12-17 at 11 35 12 PM

Screenshot 2024-12-17 at 11 45 15 PM

**Comment by a-wong-8** [comment]
I dont know @gevuong there is a gap now since there are variations in length. 
Screenshot 2024-12-18 at 6 56 31 PM

**Comment by gevuong** [comment]
I think that's fine having a gap between texts rather than underneath the last text ("Read More"). They html elements will remain in line in every card.

**Comment by a-wong-8** [comment]
localhost_3000_en_news

**Comment by a-wong-8** [comment]
localhost_3000_en_news

**Comment by gevuong** [comment]
localhost_3000_en_news
localhost_3000_en_news (1)
localhost_3000_en_news (2)

**Review by gevuong — APPROVED** [review]
@a-wong-8 Not sure if you're able to review your own PR. I'm going to approve it but please review my changes and lmk if there's anything wrong. Otherwise, merge when ready.

**Comment by a-wong-8** [comment]
excellent work, thanks @gevuong

**Pull request merged**
